### DISCUSSION TITLE
Deny organizations:LeaveOrganization per SCP

### DISCUSSION THREAD

**Discussion by sbstjn** [superwerker/superwerker#294] [Ideas]
We should add a SCP which prevents AWS accounts to leave the organization.

```yaml
- Sid: PreventLeavingOrganization
  Effect: Deny
  Action:
   - 'organizations:LeaveOrganization'
  Resource: '*'
```

I found the snippet at https://dev.to/aws-heroes/adding-aws-sso-and-controlling-permissions-56ga by [m_lewis](https://twitter.com/m_lewis)
