### ISSUE TITLE
Reduce irrelevant choices in account factory

### ISSUE THREAD

**Issue by yawn** [superwerker/superwerker#21]
Wrap account factory with UUID email aliases to delegated root email domain and call the "real" account factory.

**Comment by s0enke** [comment]
descope from 1.0

**Comment by sbstjn** [comment]
I do not understand what's needed to solve this issue.

Do you want to build some custom UI to create new accounts?
Where do you want to have this? Some custom Service Catalog thingy?

I guess, this topic involves some detailed discussions. Descope from 1.1 ? ;)

**Comment by yawn** [comment]
Oh sorry, most *def* descope from 1.1 (it's not a bug). I think we have to discuss what exactly we really want here. Candidates include at least:

- On every update of CT updating the SC product to wrap the original one and supplying root email aliases as addresses (making the email choices in the CT GUI irrelevant)
- Creating a new SC product that calls the CT product with root email aliases and advertise this as the new standard via the dashboard

Maybe I miss something else?

**Comment by sbstjn** [comment]
A custom SC product sounds okay-ish. Or we can just decide not do this and create more awareness for the RootMail feature and how to make use of it when creating additional AWS accounts.

**Comment by yawn** [comment]
That would require the customers to call some lambda function to get an email address. Not really ideal IMHO ...

**Comment by sbstjn** [comment]
Why do you want to call a lambda function?

**Comment by yawn** [comment]
To get a new email address to put into the appropriate dialogue in the CT UI ...?

**Comment by s0enke** [comment]
Since this has been descoped from 1.0 and now also 1.1 (I would rather have it in there), I'd like at least to re-add it to 1.2: We currently completely leave the user alone with workload account creation. They even don't know there is a mechanism to create root email addresses, so they also don't know they would need one. If they knew, they would not know how to create one without reverse-engineering superwerker (to find out that they need to call a Lambda). One of our recent users had the same struggle:

> And is there a guide to adding a workload account + AWSPowerUser (say)? I've been through a bunch of pages, but get a bit lost on the SSO vs CT account terminology. I created an account, but not sure how to create a power user (to install / deploy an app env)

https://og-aws.slack.com/archives/C01CQ34TC93/p1616420425004600

@yawn @sbstjn since you descoped it from 1.1, what do you think? Shall we prioritize this again?

**Comment by sbstjn** [comment]
@yarn:
Can't I just use `root+account-purpose@domain.tld` for a new account? Is it really needed to "generate" a new email address?

@s0enke:
If the solution to this is to create a custom UI, I don't think we can do this at the moment.

**Comment by yawn** [comment]
We descoped this initially from 1.1 to give priority to bugs. Now customers and users stumble upon the issue (or rather the lack of documentation) e.g. in #174. I think the issue mentioned in `og-aws` was actually about _documentation_ ("what's next") and not so much about having an account vending machine that uses our root mail email solution but MMMV.

Regarding @sbstjn's comment: sure, we can use any email address following the plus / alias style that respects the length limit that the Control Tower Service Catalogue product imposes. Since we cannot "intercept" the call to the product we thought the cleanest solution would be to provision our own product, document it and call the official CT product from it (using generated e-mail addresses).

Such a product would later also enable features such as "pre-filled" products (e.g. creating accounts scoped to specific SSO groups or OUs) that we can then share with dedicated parts of the organisation (e.g. by OU). Creating a new SC product should not be that hard ...

**Comment by s0enke** [comment]
> If the solution to this is to create a custom UI, I don't think we can do this at the moment.

Nope, I would go for the proposed solution of creating a new SC product which in turn creates the workload accounts via  Account Factory. Most of the code for this can hopefully be re-used from the [current pipeline fixture](https://github.com/superwerker/superwerker/blob/main/tests/account-factory.yaml)

**Comment by yawn** [comment]
So we agree - the fixture already covers quite some ground here. I'll have a go at it next ...

**Comment by s0enke** [comment]
@sbstjn had the idea to use SSM Automation. This would also remove the need for a wrapper-CFN-stack: 

```
description: Create AWS Account in Control Tower
schemaVersion: '0.3'
parameters:
  ProjectName:
    type: String
mainSteps:
  - name: GetCurrentVersion
    action: 'aws:executeAwsApi'
    inputs:
      Service: servicecatalog
      Api: DescribeProduct
      Name: AWS Control Tower Account Factory
    outputs:
      - Name: Version
        Selector: '$.ProvisioningArtifacts[0].Id'
        Type: String
  - name: ProvisionServiceCatalog
    action: 'aws:executeAwsApi'
    inputs:
      Api: ProvisionProduct
      Service: servicecatalog
      ProductName: AWS Control Tower Account Factory
      ProvisionedProductName: project-{{ProjectName}}
      ProvisioningArtifactId: '{{GetCurrentVersion.Version}}'
      ProvisioningParameters:
        - Key: ManagedOrganizationalUnit
          Value: "Project"
        - Key: AccountEmail
          Value: "root+project-{{ProjectName}}@aws.example.com"
        - Key: AccountName
          Value: "project-{{ProjectName}}"
        - Key: SSOUserEmail
          Value: "root@aws.example.com"
        - Key: SSOUserFirstName
          Value: "AWS Control Tower"
        - Key: SSOUserLastName
          Value: "Admin"
```
