### ISSUE TITLE
AWS Backup tries to use not enrolled AWS accounts. And fails …

### ISSUE THREAD

**Issue by sbstjn** [superwerker/superwerker#291]
When activating the automated backups feature in a legacy AWS environment with mixed accounts, the CloudFormation StackSet tries to naively roll out all resources to all AWS accounts. In my scenario, this fails with the following error in CloudFormation:

```
Resource handler returned message: 
Failed to Create/Update OrganizationConformancePack superwerker-backup-enforce. 
Summary: [NoAvailableConfigurationRecorderException in 27 account(s), ]
```

I assume, this is due to the StackSet configuration just using the `RootId` as deployment targets.

```yaml
  BackupResources:
    Type: AWS::CloudFormation::StackSet
    DependsOn: EnableCloudFormationStacksetsOrgAccessCustomResource
    Properties:
      StackSetName: superwerker-backup
      PermissionModel: SERVICE_MANAGED
      OperationPreferences:
        MaxConcurrentPercentage: 50
      Capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      StackInstancesGroup:
        - Regions:
            - !Ref AWS::Region
          DeploymentTargets:
            OrganizationalUnitIds:
              - !GetAtt OrganizationsLookup.RootId
```
