### ISSUE TITLE
Custom account factory

### ISSUE THREAD

**Issue by sbstjn** [superwerker/superwerker#314]
Based on the [Custom wrapper for AWS Control Tower Account Factory](https://sbstjn.com/blog/aws-control-tower-account-factory-wrapper/) blog post, we want to have a [SSM Automation](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-automation.html) to create new accounts.

Based on the experiences of using superwerker at multiple clients and the observation of other people using Control Tower, we identified common issues:

- Unclear how to handle account email addresses
- Unclear how to structure organizational units
- Confused how to use AWS Control Tower's Account Factory

With a custom SSM Automation, we can easily enforce a typical (and opinionated) pattern:

```
  - name: ProvisionServiceCatalog
    action: "aws:executeAwsApi"
    inputs:
      Api: ProvisionProduct
      Service: servicecatalog
      ProductName: AWS Control Tower Account Factory
      ProvisionedProductName: project-{{Name}}
      ProvisioningArtifactId: "{{GetCurrentVersion.Version}}"
      ProvisioningParameters:
        - Key: ManagedOrganizationalUnit
          Value: "Project"
        - Key: AccountEmail
          Value: "root+project-{{Name}}@aws.example.com"
        - Key: AccountName
          Value: "project-{{Name}}"
        - Key: SSOUserEmail
          Value: "root@aws.example.com"
        - Key: SSOUserFirstName
          Value: "AWS Control Tower"
        - Key: SSOUserLastName
          Value: "Admin"
```

Tasks

- [ ] Create a new nested stack for related resources (`tooling.yml` ?)
- [ ] Create a SSM Automation to create new AWS accounts
- [ ] Use `Sandbox` OU as hard-coded default
- [ ] Enforce `root+{{unique}}@aws.example.com` email pattern

Prerequisites

- Maybe we need to store the configured domain as a retrievable parameter

Additional Information

- An issue to add an ADR for SSM Automations exists
- This is a naive first implementation
- There is no validation for input parameters in place
- There is no customization for opinionated defaults in place
- An issue to extend this implementation exists
