### ISSUE TITLE
Budget SNS Topic has 0 Subscriptions. Monthly Budget reports delivery

### ISSUE THREAD

**Issue by idNoRD** [superwerker/superwerker#425]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### superwerker Version
[v0.17.2](https://github.com/superwerker/superwerker/releases/tag/v0.17.2)

### Expected Behaviour

Superwerker created two SNS topics:
- superwerker-Notifications SNS topic has 1 Subscriptions.
- superwerker-Budget SNS topic has 0 Subscriptions. It looks weird. If we don't have subscriptions why we need SNS topic then?

Looks like monthly Budget reports are not delivered. I use superwerker less than a month so I don't have proof. 

Example of solution:
```
Resources:
 BudgetNotification:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref NotificationsMail
        Protocol: email

Resources:
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref NotificationsMail
        Protocol: email
```

### Actual Behaviour
Currently budget.yaml has 0 Subscription properties for BudgetNotification SNS topic
https://github.com/superwerker/superwerker/blob/main/templates/budget.yaml#L138
```
Resources:
 BudgetNotification:
    Type: AWS::SNS::Topic
```
